### ISSUE TITLE
Sphinx 1.8+ build directory

### ISSUE THREAD

**Issue by larrybradley** [astropy/sphinx-astropy#12]
After upgrading to `Sphinx 1.8.1` (from `1.7.9`)  I noticed that when building docs locally the output Sphinx directory is now `docs/_build/html` (i.e. `<packagename>/docs/docs/_build_html`) instead of the usual `_build/html` (i.e. `<packagename>/docs/_build_html`).  I'm not sure if this is a feature or bug (and if we need to provide a workaround for the upstream change).  I noticed this in `photutils` because the `docs/docs/` started showing up as untracked files.  I'll update `.gitignore` to change `docs/_build` to just `_build` to fix that.  Astropy already has `_build` in `.gitignore` so the new output directory doesn't show up as untracked files (`_build` is the only thing under `docs/docs`).

**Comment by pllim** [comment]
@larrybradley , did you report this upstream to Sphinx? Did you ever find out if this is a bug or feature?

**Comment by astrofrog** [comment]
I don't think it's Sphinx bug as such, in that if we run ``make html`` the output directory is correct.

**Comment by astrofrog** [comment]
@larrybradley - can you check whether things work with the latest developer version of astropy? (or rc1). I fixed this in astropy-helpers. Make sure your astropy-helpers module is up-to-date.

**Comment by larrybradley** [comment]
@astrofrog  I checked both `astropy` and `photutils` (where I first noticed this) and both work with the updates.  Thanks!
