### ISSUE TITLE
Numpydoc new feature to cross-reference type

### ISSUE THREAD

**Issue by saimn** [astropy/sphinx-astropy#20]
Numpydoc 0.9 has a nice new feature to automatically cross-reference types:
https://github.com/numpy/numpydoc/pull/197/files#diff-b50754a7065a1dece18f634c6b5b2633
(their docs build is outdated, so I'm linking directly the PR).
It allows to link automatically the Python types, but also all references from intersphinx, and user defined aliases for specific terms like `array_like`.
I have been playing with this in MPDAF and it works quite well, even if themes need to be updated for a better rendering:
https://git-cral.univ-lyon1.fr/MUSE/mpdaf/blob/master/doc/conf.py#L89-102

**Comment by bsipocz** [comment]
This would be very nice to have!
