### ISSUE TITLE
Release v1.4

### ISSUE THREAD

**Issue by pllim** [astropy/sphinx-astropy#43]
It has been a year. It is time. Also `astropy/astropy` needs #40

**Comment by pllim** [comment]
I tagged v1.4 but the `publish.yml` didn't work. I have a feeling `github.event_name == 'tags'` is incorrect.

**Comment by saimn** [comment]
Indeed, `tags` is not listed here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#webhook-events
Not sure where I got this.

**Comment by pllim** [comment]
What do I do now? Do I have to retag?

**Comment by pllim** [comment]
Fixed in #44 and retagged.

**Comment by pllim** [comment]
We got close... upload failed.

**Comment by pllim** [comment]
https://pypi.org/project/sphinx-astropy/1.4/

**Comment by bsipocz** [comment]
> We got close... upload failed.

so you just restarted, or it needed more nudging?

**Comment by pllim** [comment]
I retagged and repushed. 😅
