### ISSUE TITLE
BUG: warning should not be shown to packages not using the plot directive

### ISSUE THREAD

**Issue by bsipocz** [astropy/sphinx-astropy#70]
I see this warning in the pyvo docs build logs:

```
/home/docs/checkouts/readthedocs.org/user_builds/pyvo/envs/latest/lib/python3.10/site-packages/sphinx_astropy/conf/v1.py:221: UserWarning: matplotlib's plot_directive could not be imported. Inline plots will not be included in the output
```

We don't use the plot directive, or mpl, in the docs, so this should not be shown. (I suppose, but haven't looked into it, that it shows up as we don't install mpl for the docs at all)

**Comment by pllim** [comment]
Interesting... this package seems to just assume people are going to use it.

https://github.com/astropy/sphinx-astropy/blob/54421f504c3a5c253a9283c2066043c9dd3adbc4/sphinx_astropy/conf/v1.py#L214-L223

Originally added by mdboom 11 years ago.

**Comment by pllim** [comment]
So I think this is more like a feature request to opt out, rather than a bug. As it does not look like the original design let you opt out.

**Comment by bsipocz** [comment]
Well, with my pyvo maintainer hat on, I think this is a bug that can be addressed by adding the opt-out feature :)

I would be the best though if we could do it automatically, e.g. still raise the warning, or even an exception, if there is a plot directive but mpl is missing.

**Comment by bsipocz** [comment]
In fact, I think we should always error out if the plot directive is used without mpl being available.

**Comment by bsipocz** [comment]
Ahh. Playing around with this, we indeed get the error when trying to use `plot::` without mpl:

```
/Users/bsipocz/munka/devel/pyvo/docs/index.rst:44: ERROR: Unknown directive type "plot".

.. plot::
   import matplotlib
   print(1, 2) [docutils]
```

So, the AI here is to treat mpl as optional dependency here, keep the try/except as it will error out anyway when used without mpl but that way we don't generate noise for those who don't use it.

**Comment by pllim** [comment]
I am open to that. I have no idea why that was originally added all those years ago anyway.

**Comment by bsipocz** [comment]
I would not be surprised if mpl/sphinx was not raising the exception at that early on. Anyway, PR is open, this was just a fun side trip in today's mysteries (e.g. why such an old sphinx is used in RTD...)
